version: '2'
services:
  postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSampleMicroservice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devuser
    ports:
      - 5432:5432
